pk_invoice_index:
    path: /
    controller: 'Ktarila\InvoiceBundle\Controller\InvoiceController::index'

pk_invoice_new:
    path: /new
    controller: 'Ktarila\InvoiceBundle\Controller\InvoiceController::new'

pk_invoice_edit:
    path: /edit/{invoiceId}
    controller: 'Ktarila\InvoiceBundle\Controller\InvoiceController::update'

pk_invoice_show:
    path: /show/{invoiceId}
    controller: 'Ktarila\InvoiceBundle\Controller\InvoiceController::show'

pk_invoice_delete:
    path: /delete/{invoiceId}
    controller: 'Ktarila\InvoiceBundle\Controller\InvoiceController::delete'
    methods: POST
