pk_invoice_index:
    path: /
    controller: 'PatrickKenekayoro\InvoiceBundle\Controller\InvoiceController::index'

pk_invoice_new:
    path: /new
    controller: 'PatrickKenekayoro\InvoiceBundle\Controller\InvoiceController::new'
