# controllers:
#     resource:
#         path: ../../../src/Controller/
#     type: attribute
# pk_invoice_index:
#     path: /pk_invoice_index
#     # the controller value has the format 'controller_class::method_name'
#     controller: PatrickKenekayoro\InvoiceBundle\Controller::index
# kernel:
#     resource: App\Kernel
#     type: attribute
patrickkenekayoro_invoice:
    path: /pk-invoice
    controller: 'PatrickKenekayoro\InvoiceBundle\Controller\InvoiceController::index'
