services:
   _defaults:
      autowire: true
      autoconfigure: true

   PatrickKenekayoro\InvoiceBundle\Controller\:
      resource: "../../../src/Controller/"
      tags: ["controller.service_arguments"]
